
services:
  # MongoDB Database
  # mongodb:
  #   image: mongo:7.0
  #   container_name: cloudblitz-mongodb
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password123
  #     MONGO_INITDB_DATABASE: cloudblitz
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #     - ./docker/mongodb/init-scripts:/docker-entrypoint-initdb.d
  #   networks:
  #     - cloudblitz-network
  #   # Healthcheck removed for production simplicity

  # Backend API
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: cloudblitz-backend
    restart: always
    env_file:
      - ./Server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./Server/.env:/app/.env:ro
    networks:
      - cloudblitz-network
    # depends_on:
    #   - mongodb

  # Frontend Web App
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: cloudblitz-frontend
    restart: always
    env_file:
      - ./Client/.env
    ports:
      - "3000:80"
    networks:
      - cloudblitz-network
    depends_on:
      - backend

volumes:
  mongodb_data:
    driver: local

networks:
  cloudblitz-network:
    driver: bridge